import Foundation

// ─────────────────────────────────────────────
//  BrandDirectory
//  Maps brand names → their official website
//  domains. Used by ProductWebSearchService
//  to search a brand's own site for ingredients.
// ─────────────────────────────────────────────

enum BrandDirectory {

    /// Returns the website domain for a brand (case-insensitive).
    static func domain(for brand: String) -> String? {
        let key = brand.lowercased()
            .trimmingCharacters(in: .whitespaces)
            .replacingOccurrences(of: "'", with: "")
            .replacingOccurrences(of: "'", with: "")
        // Try exact match first, then partial
        if let hit = db[key] { return hit }
        for (k, v) in db where key.contains(k) || k.contains(key) { return v }
        return nil
    }

    // MARK: — Brand → Domain

    private static let db: [String: String] = [

        // ── SKINCARE ───────────────────────────────────────────────────
        "cerave":               "cerave.com",
        "cetaphil":             "cetaphil.com",
        "neutrogena":           "neutrogena.com",
        "la roche-posay":       "laroche-posay.us",
        "la roche posay":       "laroche-posay.us",
        "laroche-posay":        "laroche-posay.us",
        "vichy":                "vichyusa.com",
        "avene":                "aveneusa.com",
        "avène":                "aveneusa.com",
        "bioderma":             "bioderma.com",
        "nuxe":                 "nuxe.com",
        "uriage":               "uriage-us.com",
        "svr":                  "laboratoiresvr.com",
        "eucerin":              "eucerin.com",
        "vanicream":            "vanicream.com",
        "aveeno":               "aveeno.com",
        "kiehl's":              "kiehls.com",
        "kiehls":               "kiehls.com",
        "origins":              "origins.com",
        "clinique":             "clinique.com",
        "estee lauder":         "esteelauder.com",
        "estée lauder":         "esteelauder.com",
        "lancome":              "lancome-usa.com",
        "lancôme":              "lancome-usa.com",
        "shiseido":             "shiseido.com",
        "tatcha":               "tatcha.com",
        "drunk elephant":       "drunkelephant.com",
        "paulas choice":        "paulaschoice.com",
        "paula's choice":       "paulaschoice.com",
        "sunday riley":         "sundayriley.com",
        "peter thomas roth":    "peterthomasroth.com",
        "mario badescu":        "mariobadescu.com",
        "the ordinary":         "theordinary.com",
        "inkey list":           "theinkeylist.com",
        "the inkey list":       "theinkeylist.com",
        "ordinary":             "theordinary.com",
        "first aid beauty":     "firstaidbeauty.com",
        "fab":                  "firstaidbeauty.com",
        "belif":                "belifinc.com",
        "innisfree":            "us.innisfree.com",
        "cosrx":                "cosrx.com",
        "some by mi":           "somebymi.com",
        "klairs":               "klairs.com",
        "dear klairs":          "klairs.com",
        "pyunkang yul":         "pyunkangyul.us",
        "anua":                 "anuaofficial.com",
        "isntree":              "isntree.com",
        "torriden":             "torridenskin.com",
        "round lab":            "roundlabofficial.com",
        "skin1004":             "skin1004.com",

        // ── MAKEUP ─────────────────────────────────────────────────────
        "maybelline":           "maybelline.com",
        "loreal":               "lorealparisusa.com",
        "l'oreal":              "lorealparisusa.com",
        "loreal paris":         "lorealparisusa.com",
        "l'oréal paris":        "lorealparisusa.com",
        "revlon":               "revlon.com",
        "nyx":                  "nyxcosmetics.com",
        "nyx cosmetics":        "nyxcosmetics.com",
        "elf":                  "elfcosmetics.com",
        "e.l.f":                "elfcosmetics.com",
        "e.l.f.":               "elfcosmetics.com",
        "milani":               "milanicosmetics.com",
        "colourpop":            "colourpop.com",
        "morphe":               "morphe.com",
        "wet n wild":           "wetnwildbeauty.com",
        "wet 'n' wild":         "wetnwildbeauty.com",
        "catrice":              "catrice.eu",
        "essence":              "essence.eu",
        "nars":                 "narscosmetics.com",
        "urban decay":          "urbandecay.com",
        "too faced":            "toofaced.com",
        "tarte":                "tartecosmetics.com",
        "benefit":              "benefitcosmetics.com",
        "mac":                  "maccosmetics.com",
        "mac cosmetics":        "maccosmetics.com",
        "charlotte tilbury":    "charlottetilbury.com",
        "fenty beauty":         "fentybeauty.com",
        "rare beauty":          "rarebeauty.com",
        "kylie cosmetics":      "kyliecosmetics.com",
        "huda beauty":          "hudabeauty.com",
        "pat mcgrath":          "patmcgrath.com",
        "armani beauty":        "giorgioarmanibeauty-usa.com",
        "ilia":                 "iliabeauty.com",
        "kosas":                "kosas.com",
        "merit":                "meritbeauty.com",
        "tower 28":             "tower28beauty.com",
        "jones road":           "jonesroadbeauty.com",
        "westman atelier":      "westmanatelier.com",

        // ── BODY CARE ──────────────────────────────────────────────────
        "dove":                 "dove.com",
        "nivea":                "niveausa.com",
        "palmers":              "palmers.com",
        "palmer's":             "palmers.com",
        "vaseline":             "vaseline.us",
        "jergens":              "jergens.com",
        "lubriderm":            "lubriderm.com",
        "gold bond":            "goldbond.com",
        "st ives":              "stives.com",
        "st. ives":             "stives.com",
        "olay":                 "olay.com",
        "ambi":                 "ambicare.com",
        "softsoap":             "softsoap.com",
        "bath body works":      "bathandbodyworks.com",
        "bath & body works":    "bathandbodyworks.com",
        "the body shop":        "thebodyshop.com",
        "body shop":            "thebodyshop.com",
        "lush":                 "lush.com",
        "rituals":              "rituals.com",
        "l'occitane":           "loccitane.com",
        "loccitane":            "loccitane.com",

        // ── HAIR CARE ──────────────────────────────────────────────────
        "pantene":              "pantene.com",
        "head shoulders":       "headandshoulders.com",
        "head & shoulders":     "headandshoulders.com",
        "tresemme":             "tresemme.com",
        "tresemmé":             "tresemme.com",
        "herbal essences":      "herbalessences.com",
        "garnier":              "garnierusa.com",
        "redken":               "redken.com",
        "kenra":                "kenra.com",
        "olaplex":              "olaplex.com",
        "joico":                "joico.com",
        "moroccanoil":          "moroccanoil.com",
        "ogx":                  "ogxbeauty.com",
        "not your mothers":     "notyourmothers.com",
        "not your mother's":    "notyourmothers.com",
        "mielle":               "mielleorganics.com",
        "cantu":                "cantubeauty.com",
        "shea moisture":        "sheamoisture.com",
        "sheamoisture":         "sheamoisture.com",
        "briogeo":              "briogeo.com",
        "amika":                "loveamika.com",
        "verb":                 "verbproducts.com",
        "schwarzkopf":          "schwarzkopfusa.com",
        "wella":                "wella.com",
        "paul mitchell":        "paulmitchell.com",
        "bumble bumble":        "bumbleandbumble.com",

        // ── SUN CARE ───────────────────────────────────────────────────
        "coppertone":           "coppertone.com",
        "banana boat":          "bananaboat.com",
        "hawaiian tropic":      "hawaiiantropic.com",
        "eltamd":               "eltamd.com",
        "supergoop":            "supergoop.com",
        "sun bum":              "sunbum.com",
        "blue lizard":          "bluelizard.net",
        "cotz":                 "cotzplus.com",
        "isdin":                "isdin.com",
        "altruist":             "altruistsun.com",

        // ── FRAGRANCE ──────────────────────────────────────────────────
        "chanel":               "chanel.com",
        "dior":                 "dior.com",
        "ysl":                  "yslbeautyus.com",
        "yves saint laurent":   "yslbeautyus.com",
        "versace":              "versace.com",
        "gucci":                "gucci.com",
        "prada":                "prada.com",
        "dolce gabbana":        "dolcegabbana.com",
        "dolce & gabbana":      "dolcegabbana.com",
        "calvin klein":         "calvinklein.com",
        "burberry":             "burberry.com",
        "marc jacobs":          "marcjacobs.com",
        "jo malone":            "jomalone.com",

        // ── AUSTRALIAN BRANDS ──────────────────────────────────────────
        "sukin":                "sukin.com.au",
        "aesop":                "aesop.com",
        "aspect":               "aspectskincare.com.au",
        "jurlique":             "jurlique.com.au",
        "natio":                "natio.com.au",
        "moogoo":               "moogoo.com.au",
        "trilogy":              "trilogyproducts.com",
        "napoleon perdis":      "napoleonperdis.com",
        "inika":                "inikaorganic.com",
        "asap":                 "asapskinsolutions.com.au",
        "alpha-h":              "alpha-h.com",
        "alpha h":              "alpha-h.com",
        "cosmedix":             "cosmedix.com",
        "dermalogica":          "dermalogica.com",

        // ── EUROPEAN BRANDS ────────────────────────────────────────────
        "weleda":               "weleda.com",
        "clarins":              "clarinsusa.com",
        "yves rocher":          "yvesrocher.us",
        "caudalie":             "caudalieusa.com",
        "filorga":              "filorga.com",
        "payot":                "payot.com",
        "lierac":               "lierac.com",
        "naf naf":              "nafnaf.com",
        "embryolisse":          "embryolisse.com",
        "cattier":              "cattier-paris.com",
        "cien":                 "lidl.de",
        "alverde":              "alverde.de",
        "alterra":              "alterra-naturkosmetik.de",
        "sebamed":              "sebamed.com",
    ]
}
